baseURL = 'https://birked.al/'
languageCode = 'en-us'
title = 'Oleoleole'
summaryLength = 10

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  showMenuItems = 3

  # center theme with default width
  centerTheme = true
  fullWidthTheme = false

[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v3'

[languages]
  [languages.en]
    languageName = "English"
    title = "birked.al"

    [languages.en.params.logo]
      logoText = "birked.al"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Github"
        url = "https://github.com/termoose"
